train_config:
  max_epoch : 3
  spilt : 0.95
  lr : 1.e-4
  eta_min : 1.e-5
  betas: [0.9, 0.99]
  weight_decay : 1.e-4
  topk : 3
  start_beta : 0
  end_beta : 1
  pe_heads : 2
  pe_bottle : 4096
  pe_dropout : 0
  load_E : False

dataloader_config:
  batch_size : 8
  shuffle : True
  num_workers : 1
  persistent_workers : True


generate_config:
  # no_repeat_ngram_size: 6
  do_sample: False
  # top_k: 50
  top_p: 1.0
  num_beams: 1
  # bad_words_ids: null
  
generate_config_es:
  # no_repeat_ngram_size: 6
  do_sample: True
  top_k: 50
  top_p: 0.9
  num_beams: 1
  temperature: 1.0


seed: 708
